// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package models

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel struct {
	ID        int32              `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	YtID      string             `json:"yt_id"`
}

type Video struct {
	ID                   int32              `json:"id"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	YtID                 string             `json:"yt_id"`
	Title                string             `json:"title"`
	Tags                 string             `json:"tags"`
	DefaultLanguage      string             `json:"default_language"`
	Description          string             `json:"description"`
	DescFts              interface{}        `json:"desc_fts"`
	LiveBroadcastContent bool               `json:"live_broadcast_content"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	ChannelID            int32              `json:"channel_id"`
}
